# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materia',
            new_name='Materias',
        ),
    ]
