# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0002_auto_20171012_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompleto', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('foto', models.FileField(upload_to='viacadapp/profilephoto')),
                ('materia', models.CharField(max_length=34)),
                ('cualidades', models.CharField(max_length=250)),
            ],
        ),
    ]
