# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0005_auto_20171027_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='materia',
            field=models.CharField(max_length=250),
        ),
    ]
