# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0006_auto_20171027_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='costohora',
        ),
    ]
