# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0009_registro_costohora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompleto', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=32)),
            ],
        ),
    ]
