# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0010_alumnos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='contraseña',
            new_name='contraseñaal',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='correo',
            new_name='correoal',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='nombrecompleto',
            new_name='nombrecompletoal',
        ),
    ]
