# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0011_auto_20171112_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materias',
            options={'managed': False},
        ),
    ]
