# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0014_auto_20171118_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
