# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0016_auto_20171120_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='foto',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
