# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viacadapp', '0019_auto_20171120_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votaciones',
        ),
    ]
